CREATE TABLE scinnob_Contact (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,  
  name VARCHAR(50) NOT NULL, 
  email VARCHAR(50) NOT NULL, 
  message TEXT, 
  ser_Web BOOLEAN DEFAULT FALSE, 
  ser_Mobile BOOLEAN DEFAULT FALSE, 
  ser_both BOOLEAN DEFAULT FALSE
  
);
